### ISSUE TITLE
[Technical] Spike frontend - map

### ISSUE THREAD

**Issue by MrHardcode** [Hold-Krykke/3SemProject_FrontEnd#19]
### How do we view a single country
* Use child path of original Europe SVG-map
* Use separate SVG map for each country
* Use external map service (Powered By Goolge map?)
* Outsource the map view
* Use viebowx to navigate and zoom map

### Conclusion
* Using svg with path for each country
* Using viewbox to map and zoom
https://github.com/Hold-Krykke/3SemProject_FrontEnd/pull/28

**Comment by Runi-VN** [comment]
https://stackoverflow.com/questions/6952986/can-i-zoom-an-svg-sample-object-to-fill-its-container

**Comment by MrHardcode** [comment]
We need to spend time figuring out these things if a related user story is chosen. If the PO doesn't even want a country map view with clickable cities, then this spike will be irrelevant. I have created [this](https://github.com/Hold-Krykke/3SemProject_FrontEnd/issues/21) user story and labeled it large which should give us enough time to figure everything all the map-related things out. 
I think this spike should be closed (based on what Pablo told us at the last meeting)
Please comment if you disagree

**Comment by Runi-VN** [comment]
@Castau has suggested using the following map:
https://simplemaps.com/resources/svg-europe

And is currently looking into zooming using viewbox.
