### ISSUE TITLE
[BUG] Selecting Events cross months

### ISSUE THREAD

**Issue by MalteMagnussen** [Hold-Krykke/3SemProject_FrontEnd#27]
When you select events with dates that span across months, you get the following error:

message: "Server returned HTTP response code: 400 for URL: https://app.ticketmaster.com/discovery/v2/events.json?geoPoint=u4xsudc0f&radius=5&unit=km&startDateTime=2019-11-27T00%3A00%3A00Z&endDateTime=2019-12-3T23%3A59%3A59Z&apikey=PXLz8SSxwRDS9HUxwZ9LVAkQELNMbma8"

or 

  "message": "Server returned HTTP response code: 400 for URL: https://app.ticketmaster.com/discovery/v2/events.json?geoPoint\u003du4xsudc0f\u0026radius\u003d5\u0026unit\u003dkm\u0026startDateTime\u003d2019-11-28T00%3A00%3A00Z\u0026endDateTime\u003d2020-11-4T23%3A59%3A59Z\u0026apikey\u003dPXLz8SSxwRDS9HUxwZ9LVAkQELNMbma8"

It looks like the parsing of the date goes wrong somehow?

**To Reproduce**
1. Go to http://localhost:3000/#/date
2. Open Modal
3. Select a start date in one month, and an end date in another. 

**Expected behavior**
Events should show. 

**Screenshots**
Selecting Date
![image](https://user-images.githubusercontent.com/11192971/69716924-5fee8100-110b-11ea-96b6-bcab7b0ac2a9.png)
Response
![image](https://user-images.githubusercontent.com/11192971/69716943-6c72d980-110b-11ea-8417-ee6d9760bdfb.png)

**Additional context**
Works fine for me if I select dates within the same month.

**Comment by Runi-VN** [comment]
This is the error returned by Ticketmaster:
```
Query param with date must be of valid format YYYY-MM-DDTHH:mm:ssZ
{example: 2020-08-01T14:00:00Z}
```

However, our parameters are:
> startDateTime=**2019-11-27**T00%3A00%3A00Z` (correct)

&
> endDateTime=**2019-12-3**T23%3A59%3A59Z (incorrect)

The error is not with spanning multiple months, it is with the date.days property only being singular.  
(e.g. **3** instead of **03**)

**EDIT**
this probably needs to be changed for months too

**Comment by MalteMagnussen** [comment]
Interesting. Nice find. So we have to change the 
![image](https://user-images.githubusercontent.com/11192971/69821983-67925080-1205-11ea-8910-288b9dbeac15.png)
parseDate method, so that IF month or date is less than 10, add a zero in front. 
Should be an easy fix. 
Again, nice find man.

**Comment by Runi-VN** [comment]
https://stackoverflow.com/a/18610204

**Comment by Runi-VN** [comment]
Needs to be fixed in both date parsers. (maybe create *one* in a util file?)
